name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: deno task build

      - name: Archive _site Artifact
        uses: actions/upload-artifact@master
        with:
          name: _site
          retention-days: 5
          path: |
            _lume/_site
            _lume/entrypoint.ts
            deno.json

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions: 
      pull-requests: write # This is required for gh bot to comment PR

    steps:
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: _site

      - name: Upload to Deno Deploy
        id: deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        uses: mathiasvr/command-output@v2.0.0
        with: 
          run: deno task deploy ${{ endsWith(github.ref, '/main') && '--prod' || '' }}

      - name: Create comment with deploy output
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with: 
          script: |
            const output = `
              ${{ steps.deploy.outputs.stdout }}

              *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })